### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by matejvasek**
* Added `DeltaBuff()` function allowing user to pass literal buffer.

### CODE REVIEW

**Comment by matejvasek** [comment]
cc @lmbarros

**Comment by matejvasek** [comment]
@lmbarros 
consider this: https://gist.github.com/matejvasek/80dc603baee319bc08d40d27db578abb
without buffer it takes 20sec
with buffer it takes 0.5sec
with buffer+inlining it takes 0.4sec

**Comment by lmbarros** [comment]
Hey @matejvasek ! Oh, I see. Reusing the buffer over and over again makes a lot of sense for your task!

I'd be happy to merge the `DeltaBuff()` change if it were alone in a separate PR. (And there's a typo in the commit message, if you want to please my nitty-picker side :smiley: )

I am not super convinced about the other change, though. I would need to take some time to look deeper but I got some other priorities right now. My current thinking here is that the speed improvement might be indeed desirable, but I am not a fan of the resulting code, which removes the abstraction layer provided by circbuf.

But here's one thing I could mention: I have fancied the idea of removing the support for non-power-of-two sizes for circbuf. I imagine this would be the best case performance-wise (no virtual call, no conditional) while still keeping the nice, readable abstraction. (I am pretty sure we (at balena) would be fine using only power-of-two block sizes, but I want to be 100% sure before going into this direction. So I still don't know if I like my idea :grimacing)

**Comment by matejvasek** [comment]
@lmbarros 

>But here's one thing I could mention: I have fancied the idea of removing the support for non-power-of-two sizes for circbuf. I imagine this would be the best case performance-wise (no virtual call, no conditional) while still keeping the nice, readable abstraction. 

I tried just using `circbuf.Po2Buffer`, it is indeed faster than using `circbuf.Buffer`. However it is not as fast as manual inlining. Performance wise it is somewhere in the middle between using interface `circbuf.Buffer` and inlining.

**Review by lmbarros — APPROVED** [review]
Thanks!

**Pull request merged**
